# VDN Configuration for Harvest Common Closed
defaults:
  - vdn_base

"ENV_NAME": "harvest_common_open"
"ENV_KWARGS":
  "num_agents": 7
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True
  "map_ASCII": ["AAA    A  WW  A    AAA",
              "AA    AAA WW AAA    AA",
              "A    AAAAAWWAAAAA    A",
              "      AAA WW AAA      ",
              "       A  WW  A       ",
              "  A       WW       A  ",
              " AAA  Q   WW   Q  AAA ",
              "AAAAA     WW     AAAAA",
              " AAA  WWWWWWWWWW  AAA ",
              "  A       WW       A  ",
              "WWWWWWWWW WW WWWWWWWWW",
              "          WW          ",
              "  WWWWWWWWWWWWWWWWWW  ",
              "  P P P P P P P P P   ",
              " P P P P P P P P P P  ",
             ]
