# VDN Configuration for Harvest Common Open
defaults:
  - vdn_base

"ENV_NAME": "harvest_common_open"
"ENV_KWARGS":
  "num_agents": 7
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True
