# MAPPO Configuration for PD Arena
defaults:
  - mappo_base

# Environment-specific settings
"ENV_NAME": "pd_arena"
"NUM_ENVS": 4
"TOTAL_TIMESTEPS": 3e8
"NUM_MINIBATCHES": 4

"ENV_KWARGS": 
  "num_agents": 4
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True

# Reward settings
"REWARD": "MAPPO"
"WANDB_TAGS": 
  - COMMON_REWARD
