"LR": 0.0005
"NUM_ENVS": 5
"NUM_STEPS": 100
"TOTAL_TIMESTEPS": 1e9
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"SCALE_CLIP_EPS": True

"ACTIVATION": "relu"
"ENV_NAME": "territory_open"
"REW_SHAPING_HORIZON": 2.5e6 # for how many timesteps add a shaping reward

"ENV_KWARGS": 
  "num_agents" : 7
  "num_inner_steps" : 1000
  "shared_rewards" : True  # Attention: switch to False for individual rewards 
  "cnn" : True
  "jit" : True
  

"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"TUNE": False

"REWARD": "MAPPO" # individual; common
"GIF_NUM_FRAMES": 250

# WandB Params
"ENTITY": ""
"PROJECT": "socialjax_mappo"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - COMMON_REWARD # COMMON_REWARD; INDIVIDUAL_REWARD
