# IPPO Configuration for Mushrooms
defaults:
  - ippo_base

# Environment-specific settings
"ENV_NAME": "mushrooms"
"LR": 0.0001

"ENV_KWARGS":
  "num_agents": 5
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True

# Reward settings
"REWARD": "common" # common; individual
"WANDB_TAGS":
  - COMMON_REWARD # COMMON_REWARD; INDIVIDUAL_REWARD
