# IPPO Configuration for Gift
defaults:
  - ippo_base
  - _self_
  - reward: common  # override on CLI: reward=individual

# Environment-specific settings
"ENV_NAME": "gift"

"ENV_KWARGS":
  "num_agents": 2
  "num_inner_steps": 1000
  "cnn": True
  "jit": True
