# IPPO Configuration for Clean Up
defaults:
  - ippo_base

# Environment-specific settings
"ENV_NAME": "clean_up"

"ENV_KWARGS":
  "num_agents": 7
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True

# Reward settings
"REWARD": "common" # common; individual
"WANDB_TAGS":
  - COMMON_REWARD # COMMON_REWARD; INDIVIDUAL_REWARD
