# IPPO Configuration for PD Arena
defaults:
  - ippo_base

# Environment-specific settings
"ENV_NAME": "pd_arena"
"NUM_STEPS": 500

"ENV_KWARGS":
  "num_agents": 4
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True

# Reward settings
"REWARD": "common" # common; individual
"WANDB_TAGS":
  - COMMON_REWARD # COMMON_REWARD; INDIVIDUAL_REWARD
