# IPPO Configuration for PD Arena
defaults:
  - ippo_base

# Environment-specific settings
"ENV_NAME": "pd_arena"
"NUM_STEPS": 500

"ENV_KWARGS":
  "num_agents": 4
  "num_inner_steps": 1000
  "shared_rewards": False
  "cnn": True
  "jit": True

# Reward settings (only remark for wandb tags, as the reward type is already set in "shared_rewards")
"REWARD": "individual"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD
