# IPPO Configuration for Cooperative Mining
defaults:
  - ippo_base

# Environment-specific settings
"ENV_NAME": "coop_mining"
"NUM_MINIBATCHES": 300

"ENV_KWARGS":
  "num_agents": 4
  "num_inner_steps": 1000
  "shared_rewards": False
  "cnn": True
  "jit": True

# Reward settings
"REWARD": "individual"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD
