# TRANSFER Configuration for PD Arena
defaults:
  - transfer_base

"ENV_NAME": "pd_arena"

"ENV_KWARGS": 
  "num_agents": 4
  "num_inner_steps": 1000
  "shared_rewards": False
  "cnn": True
  "jit": True
  "svo": False
  "svo_target_agents": [0, 1, 2, 3]
  "svo_w": 0.5
  "svo_ideal_angle_degrees": 90
  "interest": True
  "s_interest_change_every": 30000000

"REWARD": "individual"
"WANDB_TAGS": 
  - INDIVIDUAL_REWARD
