"LR": 0.001
"NUM_ENVS": 128
"NUM_STEPS": 1000
"TOTAL_TIMESTEPS": 1e8
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 500
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "clean_up"
"REW_SHAPING_HORIZON": 2.5e6 # for how many timesteps add a shaping reward
"ENV_KWARGS": 
  "num_agents" : 7
  "num_inner_steps" : 1000
  "shared_rewards" : False  # Attention: switch to False for individual rewards 
  "cnn" : True
  "jit" : True 
  "inequity_aversion" : True
  "inequity_aversion_target_agents": [0, 1, 2, 3, 4, 5, 6]
  "inequity_aversion_alpha": 0.0
  "inequity_aversion_beta": 0.0
  "enable_smooth_rewards": False

"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"TUNE": True

"REWARD": "individual" # individual; common
"GIF_NUM_FRAMES": 250

# WandB Params
"ENTITY": ""
"PROJECT": "socialjax"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD # COMMON_REWARD
