# IPPO Configuration for Gift
defaults:
  - ippo_base

# Environment-specific settings
"ENV_NAME": "gift"

"ENV_KWARGS":
  "num_agents": 2
  "num_inner_steps": 1000
  "shared_rewards": False
  "cnn": True
  "jit": True

# Reward settings
"REWARD": "individual"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD
