_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 12
                - 45
                - 50
                - 55
            "2":
                - 12
                - 45
                - 50
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
ACTIVATION:
    value: relu
ANNEAL_LR:
    value: true
CLIP_EPS:
    value: 0.2
ENT_COEF:
    value: 0.01
ENTITY:
    value: ""
ENV_KWARGS:
    value:
        cnn: true
        jit: true
        num_agents: 7
        num_inner_steps: 1000
        shared_rewards: false
ENV_NAME:
    value: clean_up
GAE_LAMBDA:
    value: 0.95
GAMMA:
    value: 0.99
LR:
    value: 0.0005
MAX_GRAD_NORM:
    value: 0.5
NUM_ENVS:
    value: 256
NUM_MINIBATCHES:
    value: 50
NUM_SEEDS:
    value: 1
NUM_STEPS:
    value: 100
PROJECT:
    value: socialjax
REW_SHAPING_HORIZON:
    value: 2.5e+06
REWARD:
    value: individual
SEED:
    value: 30
TOTAL_TIMESTEPS:
    value: 1e+07
TUNE:
    value: false
UPDATE_EPOCHS:
    value: 2
VF_COEF:
    value: 0.5
WANDB_MODE:
    value: online
WANDB_TAGS:
    value:
        - INDIVIDUAL_REWARD
