name: Speed_example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jaxlib==0.4.23+cuda11.cudnn86 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
        pip install pylint
        
    - name: pylink test code
      continue-on-error: true
      env:
        PYTHONPATH: ./socialjax:${{ env.PYTHONPATH }}
      run: |
        pylint speed_test/speed_test_random.py
    - name: run test speed code
      continue-on-error: true
      env:
        PYTHONPATH: ./socialjax:${{ env.PYTHONPATH }}
      run: |
        python speed_test/speed_test_random.py

